name: Deploy PWA to GitHub Pages

# Executa o script sempre que houver um push na branch principal (main ou master)
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

# Permissões necessárias para o GitHub Actions publicar na página
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Versão estável do Node

      - name: Instalar Dependências
        run: npm install

      - name: Compilar o TypeScript (Gera a pasta dist)
        run: npm run build

      - name: Configurar o GitHub Pages
        uses: actions/configure-pages@v4

      - name: Fazer o Upload dos Ficheiros (Artefato)
        uses: actions/upload-pages-artifact@v3
        with:
          # Faz o upload de todo o diretório atual, que agora inclui a pasta dist compilada pelo Actions
          path: '.' 

      - name: Publicar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
